[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:api-gateway]
command=uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir /app/api_gateway
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app"

[program:ingestion]
command=uvicorn main:app --host 0.0.0.0 --port 8001 --app-dir /app/ingestion
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app"

[program:analysis]
command=uvicorn main:app --host 0.0.0.0 --port 8002 --app-dir /app/analysis
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app"

[program:delivery]
command=uvicorn main:app --host 0.0.0.0 --port 8003 --app-dir /app/delivery
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app"
