# =============================================================================
# app/models.py — delivery-service
# =============================================================================
# Internal Pydantic models for the delivery service.
# =============================================================================

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


class CreatorContext(BaseModel):
    """
    Creator DNA profile used for idea personalisation.
    Loaded from creator_profiles table.
    """
    creator_id: int
    tiktok_handle: str
    primary_niche: str
    secondary_niches: list[str] = []
    tone: str
    hook_style: str
    avg_video_length: str
    audience_type: str
    content_style: str
    raw_dna: dict = {}


class AngleContext(BaseModel):
    """
    A content angle from the angle library.
    Passed to Claude for personalisation.
    """
    angle_id: int
    angle_name: str
    angle_type: str
    hook_formula: str
    hook_example: str
    why_it_works: str
    shot_list: list[str]
    cta: str
    source_revenue: str
    source_niche: str


class GeneratedIdea(BaseModel):
    """
    A personalised content idea generated by Claude.
    Written in the creator's specific voice and style.
    """
    hook: str
    shot_list: list[str]
    cta: str
    angle_type: str
    angle_id: int
    source_revenue: str
    why_this_works: str


class DeliveryResult(BaseModel):
    """
    Summary of a completed delivery run for one creator.
    """
    creator_id: int
    tiktok_handle: str
    ideas_generated: int
    status: str             # 'success' | 'error'
    error_message: Optional[str] = None
    ran_at: datetime = Field(default_factory=datetime.now)
